version: "3"

services:
  bandapi:
    build: .
    image: bands
    networks:
      - backend
    environment: 
      - MONGO_URL=mongodb
      - JWT_SECRET=1SD5F18EW3IJFSOFSD
      - JWT_EXPIRY_MINUTES=15
      - PORT=8000
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=bands-users
      - MONGO_TIMEOUT=30
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    networks:
      - backend
    ports:
      - "27777:27017"
networks:
  backend:
