version: "3"

services:
  bandsapi:
    build: .
    image: github.com/paoloposso/bands-auth-api
    networks:
      - backend
    environment:
      - JWT_SECRET=ad9Hyd98879JKYid7X987as
      - JWT_EXPIRY_MINUTES=15
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=bands-users
    ports:
      - "9900:80"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    networks:
      - backend
    ports:
      - "27777:27017"
networks:
  backend:
