basePath: /api/v1
definitions:
  api.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  api.LoginResponse:
    properties:
      email:
        type: string
      name:
        type: string
      token:
        type: string
    type: object
  api.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - name
    type: object
  api.ValidateTokenResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  description: Authentication and Registration API.
  title: Bands Auth API
  version: "1.0"
paths:
  /is-alive:
    get:
      consumes:
      - application/json
      description: Tells if the auth APIs are working or not.
      produces:
      - application/json
      responses:
        "200":
          description: api response
          schema:
            type: string
      summary: This API can be used as health check for this application.
      tags:
      - Health Check
  /user:
    post:
      consumes:
      - application/json
      description: Registers an User.
      parameters:
      - description: User Registration
        in: body
        name: userRegistration
        required: true
        schema:
          $ref: '#/definitions/api.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ""
      summary: This API can be used to register an User.
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: User Login.
      parameters:
      - description: Login Request
        in: body
        name: login_request
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: api response
          schema:
            $ref: '#/definitions/api.LoginResponse'
      summary: This API can be used authenticate an User.
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Validate Token
      parameters:
      - description: Token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: api response
          schema:
            $ref: '#/definitions/api.ValidateTokenResponse'
      summary: This API can be used to validate a token.
      tags:
      - User
swagger: "2.0"
