name: Go

on: 
  push: 
    branches: 
      — master 
      — staging
      — develop 
  pull_request: 
    branches: 
      — master 
      — staging 
      — develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x

    - name: Install
      run: |
        go get github.com/go-chi/chi
        go get github.com/gookit/validate
        go get github.com/google/uuid
          
    - name: Build
      run: go build -v ./...

    - name: Test
      run: export ENV=TEST&&go test -v ./...
