name: Go

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Get Packages
      run: |
        go get -t -v ./...
          
    - name: Build
      run: go build -v ./...

    - name: Test
      run: export ENV=TEST&&go test -v ./...
